/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intf;

/**
 *
 * @author Zues
 */
public class addTask extends javax.swing.JFrame {

    /**
     * Creates new form addTask
     */
    public addTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tasktxt = new javax.swing.JTextField();
        proftxt = new javax.swing.JComboBox<>();
        hourtxt = new javax.swing.JTextField();
        daytxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add task");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add a task...");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, 50));

        tasktxt.setBackground(new java.awt.Color(255, 255, 255));
        tasktxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tasktxt.setForeground(new java.awt.Color(0, 51, 153));
        tasktxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tasktxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 153)));
        tasktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasktxtActionPerformed(evt);
            }
        });
        jPanel2.add(tasktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 170, -1));

        proftxt.setBackground(new java.awt.Color(255, 255, 255));
        proftxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        proftxt.setForeground(new java.awt.Color(0, 51, 153));
        proftxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carpenter", "Mason", "Plumber", "Electritian" }));
        proftxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 153)));
        proftxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proftxtActionPerformed(evt);
            }
        });
        jPanel2.add(proftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 170, 30));

        hourtxt.setBackground(new java.awt.Color(255, 255, 255));
        hourtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hourtxt.setForeground(new java.awt.Color(0, 51, 153));
        hourtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hourtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 153)));
        hourtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourtxtActionPerformed(evt);
            }
        });
        jPanel2.add(hourtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 170, 30));

        daytxt.setBackground(new java.awt.Color(255, 255, 255));
        daytxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        daytxt.setForeground(new java.awt.Color(0, 51, 153));
        daytxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        daytxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 153)));
        daytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daytxtActionPerformed(evt);
            }
        });
        jPanel2.add(daytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 170, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Task name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("profession :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hours worked :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Days worked :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        addbtn.setBackground(new java.awt.Color(0, 153, 51));
        addbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel2.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 130, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 590, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proftxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proftxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proftxtActionPerformed

    private void daytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daytxtActionPerformed

    private void tasktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tasktxtActionPerformed

    private void hourtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourtxtActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String chosenName =  (String) proftxt.getSelectedItem();
        projectTab.AddTask(tasktxt.getText(),chosenName,hourtxt.getText(),daytxt.getText());
        projectTab.fcost = projectTab.fcost + projectTab.fullCost(chosenName,hourtxt.getText(),daytxt.getText());
        projectTab.tDays = projectTab.tDays + Integer.parseInt(daytxt.getText());
        this.dispose();
    }//GEN-LAST:event_addbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField daytxt;
    private javax.swing.JTextField hourtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> proftxt;
    private javax.swing.JTextField tasktxt;
    // End of variables declaration//GEN-END:variables
}
