/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intf;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Zues
 */
public class projectTab extends javax.swing.JFrame {

    static double fcost;
    static int tDays;
    static String date;
    static String time;
    
    
    /**
     * Creates new form projectTab
     */
    public projectTab() {
        initComponents();
         dt(); // daet
        
        times(); // time
        
    }

    
    public void dt(){

    Date d  =new Date();
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
    
    String dd = sdf.format(d);
    date = dd;


}
   
// time
 Timer t ;
 SimpleDateFormat st ;
    
public void times(){

   
    
  t = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        Date dt  =new Date();
        st = new SimpleDateFormat("hh:mm:ss a");
        
        String tt = st.format(dt);
        time = tt;
        
        }
    });
  
    t.start();
    
    

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addProbtn = new javax.swing.JButton();
        addtaskbtn = new javax.swing.JButton();
        finalCostbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projects");
        setMinimumSize(new java.awt.Dimension(1252, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Project... ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 50));

        addProbtn.setBackground(new java.awt.Color(0, 153, 0));
        addProbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addProbtn.setForeground(new java.awt.Color(255, 255, 255));
        addProbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/icons/icons8-add-48.png"))); // NOI18N
        addProbtn.setText("Add project name");
        addProbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProbtnActionPerformed(evt);
            }
        });
        jPanel2.add(addProbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 230, 50));

        addtaskbtn.setBackground(new java.awt.Color(0, 51, 153));
        addtaskbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addtaskbtn.setForeground(new java.awt.Color(255, 255, 255));
        addtaskbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/icons/icons8-add-48.png"))); // NOI18N
        addtaskbtn.setText("Add task                 ");
        addtaskbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtaskbtnActionPerformed(evt);
            }
        });
        jPanel2.add(addtaskbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 230, 50));

        finalCostbtn.setBackground(new java.awt.Color(255, 255, 0));
        finalCostbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        finalCostbtn.setForeground(new java.awt.Color(0, 51, 153));
        finalCostbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/icons/icons8-price-tag-40.png"))); // NOI18N
        finalCostbtn.setText("Final cost               ");
        finalCostbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalCostbtnActionPerformed(evt);
            }
        });
        jPanel2.add(finalCostbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 230, 50));

        resetbtn.setBackground(new java.awt.Color(204, 0, 0));
        resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(255, 255, 255));
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        jPanel2.add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 230, 50));

        txtArea.setBackground(new java.awt.Color(204, 204, 204));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtArea.setForeground(new java.awt.Color(0, 0, 0));
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 730, 490));

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jTextArea2.setText("\t\t\n\t\t                    WMS PROJECT MANAGEMENT\n\n");
        jTextArea2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane3.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 730, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 750));

        backbtn.setBackground(new java.awt.Color(0, 51, 153));
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intf/icons/icons8-back-arrow-50.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 60, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Copyright @2023. All right reserved");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 820, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Dashboard dash1 = new Dashboard();
        dash1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void addtaskbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtaskbtnActionPerformed
       addTask task1 = new addTask();
       task1.setVisible(true);
    }//GEN-LAST:event_addtaskbtnActionPerformed

    private void finalCostbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalCostbtnActionPerformed
        txtArea.append("----------------------------------------------------------------------------------------------------------------------"+"\n");
        txtArea.append("        Total Days:     "+tDays+"                                                                                                    Final cost:  Rs.  "+fcost+"\n");
        
    }//GEN-LAST:event_finalCostbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        txtArea.setText("");
        projectTab.fcost =0;
        projectTab.tDays =0;
    }//GEN-LAST:event_resetbtnActionPerformed

    private void addProbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProbtnActionPerformed
        addProName pro1 = new addProName();
        pro1.setVisible(true);
    }//GEN-LAST:event_addProbtnActionPerformed

    public static void AddProName(String name){
        String nm = name;
        txtArea.append("       Projet Name: "+nm+"                                                                  "+"Date: "+date+"      "+"Time: "+time+"    "+"\n"+"\n"+"\n");
        txtArea.append("             Task                      Profession                        Hours worked              Days worked                Cost "+"\n");
        txtArea.append("----------------------------------------------------------------------------------------------------------------------"+"\n");
    }
    public static void AddTask(String task,String profession,String hr,String day){
        String taskName = task;
        String prof = profession;
        int hourRate;
        double cost = 0;
        int hour = Integer.parseInt(hr);
        int days = Integer.parseInt(day);
        
        if (prof.equals("Carpenter")){
            hourRate =500;
            cost = hourRate*hour*days; 
            
        }
        if (prof.equals("Mason")){
            hourRate =500;
            cost = hourRate*hour*days; 
        }
        if (prof.equals("Plumber")){
            hourRate =375;
            cost = hourRate*hour*days; 
        }
        if (prof.equals("Electritian")){
            hourRate =375;
            cost = hourRate*hour*days; 
        }
        
        txtArea.append("           "+taskName+"                      "+prof+"                                   "+hour+"                                "+days+"                         "+cost+" "+"\n");
        
   }
    public static double fullCost(String profession,String hr,String day){
        String prof = profession;
        double cost = 0;
        int hourRate;
        int hour = Integer.parseInt(hr);
        int days = Integer.parseInt(day);
        
        if (prof.equals("Carpenter")){
            hourRate =500;
            cost = hourRate*hour*days; 
            
        }
        if (prof.equals("Mason")){
            hourRate =500;
            cost = hourRate*hour*days; 
        }
        if (prof.equals("Plumber")){
            hourRate =375;
            cost = hourRate*hour*days; 
        }
        if (prof.equals("Electritian")){
            hourRate =375;
            cost = hourRate*hour*days; 
        }
        return cost;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projectTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projectTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projectTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projectTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

   
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projectTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProbtn;
    private javax.swing.JButton addtaskbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton finalCostbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton resetbtn;
    public static javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
